### ISSUE TITLE
[BUG] Wazuh dashboard server is not ready yet

### ISSUE THREAD

**Issue by luffysan92** [wazuh/wazuh-dashboard#57]
**Describe the bug**

I recently upgraded wazuh following guide Upgrade for OVA https://documentation.wazuh.com/current/upgrade-guide/upgrading-central-components.html#upgrading-wazuh-server

The problem now is that when I try to access via browser it says "Wazuh dashboard server is not ready yet" and hasnt changed for a couple of days. 

I have tried restarting services and still nothing.

```
systemctl restart wazuh-dashboard
systemctl restart wazuh-indexer
systemctl restart wazuh-manager
systemctl restart filebeat
```

Still nothing.

filebeat test output
```
[root@wazuh-server /]# filebeat test output
elasticsearch: https://127.0.0.1:9200...
  parse url... OK
  connection...
    parse host... OK
    dns lookup... OK
    addresses: 127.0.0.1
    dial up... OK
  TLS...
    security: server's certificate chain verification is enabled
    handshake... OK
    TLS version: TLSv1.3
    dial up... OK
  talk to server... OK
  version: 7.10.2
[root@wazuh-server /]#
```

Is there anything that i could've done wrong in the upgrading process or is incompatibility somewhere?

**Comment by AlexRuiz7** [comment]
Hello @luffysan92 

Thank you for using Wazuh. I'm sorry to hear that you are having troubles during the upgrade process. Could you please tell me what version of Wazuh were you using before the upgrade, and the version you upgraded to?

This message usually means that there is no connectivity between the UI (Wazuh dashboard) and the backend (Wazuh indexer). The best way to know the reason is reading the logs.

The logs are stored in the `/var/logs` folder. Check [this link](https://documentation.wazuh.com/current/user-manual/wazuh-dashboard/troubleshooting.html#none-of-the-above-solutions-are-fixing-my-problem) for more info.

Let me know if that was useful. I'll be waiting for your reply.

**Comment by luffysan92** [comment]
Hi @AlexRuiz7 

Thank you for replying. Below sample errors from `cat /var/log/wazuh-indexer/wazuh-cluster.log | grep -i -E "error|warn"`

[2023-05-05T10:11:30,836][ERROR][o.o.s.s.t.SecuritySSLNettyTransport] [node-1] Exception during establishing a SSL connection: javax.net.ssl.SSLHandshakeException: Empty client certificate chain
[2023-05-05T10:11:30,837][WARN ][o.o.t.TcpTransport       ] [node-1] exception caught on transport layer [Netty4TcpChannel{localAddress=/127.0.0.1:9300, remoteAddress=/127.0.0.1:52098}], closing connection
[2023-05-05T10:11:30,850][ERROR][o.o.s.s.t.SecuritySSLNettyTransport] [node-1] Exception during establishing a SSL connection: javax.net.ssl.SSLHandshakeException: Empty client certificate chain
[2023-05-05T10:11:30,851][WARN ][o.o.t.TcpTransport       ] [node-1] exception caught on transport layer [Netty4TcpChannel{localAddress=/127.0.0.1:9300, remoteAddress=/127.0.0.1:52100}], closing connection
[2023-05-05T10:11:33,301][ERROR][o.o.s.s.t.SecuritySSLNettyTransport] [node-1] Exception during establishing a SSL connection: javax.net.ssl.SSLHandshakeException: Empty client certificate chain
[2023-05-05T10:11:33,302][WARN ][o.o.t.TcpTransport       ] [node-1] exception caught on transport layer [Netty4TcpChannel{localAddress=/127.0.0.1:9300, remoteAddress=/127.0.0.1:52102}], closing connection
[2023-05-05T10:11:33,314][ERROR][o.o.s.s.t.SecuritySSLNettyTransport] [node-1] Exception during establishing a SSL connection: javax.net.ssl.SSLHandshakeException: Empty client certificate chain
[2023-05-05T10:11:33,315][WARN ][o.o.t.TcpTransport       ] [node-1] exception caught on transport layer [Netty4TcpChannel{localAddress=/127.0.0.1:9300, remoteAddress=/127.0.0.1:52104}], closing connection
[2023-05-05T10:11:33,327][ERROR][o.o.s.s.t.SecuritySSLNettyTransport] [node-1] Exception during establishing a SSL connection: javax.net.ssl.SSLHandshakeException: Empty client certificate chain
[2023-05-05T10:11:33,328][WARN ][o.o.t.TcpTransport       ] [node-1] exception caught on transport layer [Netty4TcpChannel{localAddress=/127.0.0.1:9300, remoteAddress=/127.0.0.1:52106}], closing connection
[2023-05-05T10:11:33,352][ERROR][o.o.s.s.t.SecuritySSLNettyTransport] [node-1] Exception during establishing a SSL connection: javax.net.ssl.SSLHandshakeException: Empty client certificate chain
[2023-05-05T10:11:33,353][WARN ][o.o.t.TcpTransport       ] [node-1] exception caught on transport layer [Netty4TcpChannel{localAddress=/127.0.0.1:9300, remoteAddress=/127.0.0.1:52108}], closing connection

After closer inspection it looks like a certificate issue? 

Thanks for your help.

**Comment by luffysan92** [comment]
Hi @AlexRuiz7 

I upgraded to the latest version 4.4 following the documentation. The previous version Im sorry I didn't note it down. That is poor change management on my end. Im highly almost certain it was version 4.3. Unless there is a way to find out im happy to try.

Many thanks

**Comment by AlexRuiz7** [comment]
Thanks for the info. I'll be back to you asap

**Comment by AlexRuiz7** [comment]
Looks like a problem with the certificates indeed.

Could you please share your `opensearch_dashboards.yml`? Redact any public IP, if present.

**Comment by luffysan92** [comment]
Here it is `/etc/wazuh-dashboard/opensearch_dashboards.yml`

`server.host: x.x.x.x
opensearch.hosts: https://127.0.0.1:9300
server.port: 443
opensearch.ssl.verificationMode: certificate
opensearch.username: admin
opensearch.password: xxxxx
opensearch.requestHeadersWhitelist: ["securitytenant","Authorization"]
opensearch_security.multitenancy.enabled: false
opensearch_security.readonly_mode.roles: ["kibana_read_only"]
server.ssl.enabled: true
server.ssl.key: "/etc/wazuh-dashboard/certs/wazuh-dashboard-key.pem"
server.ssl.certificate: "/etc/wazuh-dashboard/certs/wazuh-dashboard.pem"
opensearch.ssl.certificateAuthorities: ["/etc/wazuh-dashboard/certs/root-ca.pem"]
uiSettings.overrides.defaultRoute: /app/wazuh
`

This is my `/etc/wazuh-indexer/opensearch.yml` file

`network.host: "127.0.0.1"
node.name: "node-1"
cluster.initial_master_nodes:
- "node-1"
cluster.name: "wazuh-cluster"

node.max_local_storage_nodes: "3"
path.data: /var/lib/wazuh-indexer
path.logs: /var/log/wazuh-indexer

plugins.security.ssl.http.pemcert_filepath: /etc/wazuh-indexer/certs/wazuh-indexer.pem
plugins.security.ssl.http.pemkey_filepath: /etc/wazuh-indexer/certs/wazuh-indexer-key.pem
plugins.security.ssl.http.pemtrustedcas_filepath: /etc/wazuh-indexer/certs/root-ca.pem
plugins.security.ssl.transport.pemcert_filepath: /etc/wazuh-indexer/certs/wazuh-indexer.pem
plugins.security.ssl.transport.pemkey_filepath: /etc/wazuh-indexer/certs/wazuh-indexer-key.pem
plugins.security.ssl.transport.pemtrustedcas_filepath: /etc/wazuh-indexer/certs/root-ca.pem
plugins.security.ssl.http.enabled: true
plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.ssl.transport.resolve_hostname: false

plugins.security.authcz.admin_dn:
- "CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"
plugins.security.check_snapshot_restore_write_privileges: true
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.nodes_dn:
- "CN=indexer,OU=Wazuh,O=Wazuh,L=California,C=US"
plugins.security.restapi.roles_enabled:
- "all_access"
- "security_rest_api_access"

plugins.security.system_indices.enabled: true
plugins.security.system_indices.indices: [".opendistro-alerting-config", ".opendistro-alerting-alert*", ".opendistro-anomaly-results*", ".opendistro-anomaly-detector*", ".opendistro-anomaly-checkpoints", ".opendistro-anomaly-detection-state", ".opendistro-reports-*", ".opendistro-notifications-*", ".opendistro-notebooks", ".opensearch-observability", ".opendistro-asynchronous-search-response*", ".replication-metadata-store"]

### Option to allow Filebeat-oss 7.10.2 to work ###
compatibility.override_main_response_version: true
`

I would also like to point out another problem that could be related or hopefully give meaning to my problem as well. 

When i used `bash wazuh-passwords-tool.sh -a` because i thought passwords might have been defaulted below error comes up. 

'[root@wazuh-server wazuh-user]# bash wazuh-passwords-tool.sh -a
grep: /etc/wazuh-indexer/opensearch-security/internal_users.yml: No such file or directory
06/05/2023 09:01:01 INFO: Wazuh API admin credentials not provided, Wazuh API passwords not changed.
06/05/2023 09:02:14 ERROR: The backup could not be created'

and also ran 'bash wazuh-passwords-tool.sh -a -v'

'[root@wazuh-server wazuh-user]# bash wazuh-passwords-tool.sh -a -v
grep: /etc/wazuh-indexer/opensearch-security/internal_users.yml: No such file or directory
06/05/2023 09:05:37 INFO: Wazuh API admin credentials not provided, Wazuh API passwords not changed.
mkdir: cannot create directory ‘/etc/wazuh-indexer/backup’: File exists
Security Admin v7
WARNING: Seems you want connect to the OpenSearch HTTP port.
         securityadmin connects on the transport port which is normally 9300.
Will connect to 127.0.0.1:9200 ... done
ERR: Cannot connect to OpenSearch. Please refer to opensearch logfile for more information
Trace:
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{LtaGyFmUR2mOZOBTXUkLMQ}{127.0.0.1}{127.0.0.1:9200}]]
        at org.opensearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:381)
        at org.opensearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:272)
        at org.opensearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:79)
        at org.opensearch.client.transport.TransportClient.doExecute(TransportClient.java:484)
        at org.opensearch.client.support.AbstractClient.execute(AbstractClient.java:433)
        at org.opensearch.client.support.AbstractClient.execute(AbstractClient.java:419)
        at org.opensearch.security.tools.SecurityAdmin.execute(SecurityAdmin.java:524)
        at org.opensearch.security.tools.SecurityAdmin.main(SecurityAdmin.java:157)


Successfully updated the keystore
Security Admin v7
WARNING: Seems you want connect to the OpenSearch HTTP port.
         securityadmin connects on the transport port which is normally 9300.
Will connect to 127.0.0.1:9200 ... done
ERR: Cannot connect to OpenSearch. Please refer to opensearch logfile for more information
Trace:
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{uGBnDGPAQ9mO44fdwJ2u9A}{127.0.0.1}{127.0.0.1:9200}]]
        at org.opensearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:381)
        at org.opensearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:272)
        at org.opensearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:79)
        at org.opensearch.client.transport.TransportClient.doExecute(TransportClient.java:484)
        at org.opensearch.client.support.AbstractClient.execute(AbstractClient.java:433)
        at org.opensearch.client.support.AbstractClient.execute(AbstractClient.java:419)
        at org.opensearch.security.tools.SecurityAdmin.execute(SecurityAdmin.java:524)
        at org.opensearch.security.tools.SecurityAdmin.main(SecurityAdmin.java:157)


06/05/2023 09:07:17 INFO: The password for user  is P+m(edited)dQE4b09qvl0V
06/05/2023 09:07:17 WARNING: Wazuh indexer passwords changed. Remember to update the password in the Wazuh dashboard and Filebeat nodes if necessary, and restart the services.
[root@wazuh-server wazuh-user]#
'

**Comment by luffysan92** [comment]
Hi @AlexRuiz7 I have checked the java version and its using java 11

```
[root@wazuh-server /]# java -version
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)
```

I did find that Wazuh-indexer did not upgrade from 4.3 to 4.4.1. I've now upgraded but problem still persists. 

I will need your help with the wazuh certificate. Please note I am using Wazuh OVA. I've downloaded the wazuh-certs-tool.sh and ran it `bash wazuh-certs-tool.sh -A` but error No configuration file found. I think it is referring to [config.yml](https://packages.wazuh.com/4.4/config.yml) in [Certificates Deployment](https://packages.wazuh.com/4.4/config.yml) . Where can i double check my Wazuh Indexer node name/ip, wazuh manager node name/ip and dashboard node name/ip?

Thank you for the help.

Cheers

**Comment by luffysan92** [comment]
Hi @AlexRuiz7 

After running `bash wazuh-certs-tool.sh -A /etc/wazuh-indexer/certs/root-ca.pem /etc/wazuh-indexer/certs/root-ca.key `

I got error 

```
[root@wazuh-server /]# bash wazuh-certs-tool.sh -A /etc/wazuh-indexer/certs/root-ca.pem /etc/wazuh-indexer/certs/root-ca.key
10/05/2023 08:51:42 ERROR: The file /etc/wazuh-indexer/certs/root-ca.key does not exists
[root@wazuh-server /]# ^C
[root@wazuh-server /]# cd /etc/wazuh-indexer/certs
[root@wazuh-server certs]# ls
admin-key.pem  admin.pem  root-ca.pem  wazuh-indexer-key.pem  wazuh-indexer.pem
```

**Comment by luffysan92** [comment]
Hi @AlexRuiz7 

I have done what you've suggested but still no luck.

**Comment by luffysan92** [comment]
Also `filebeat test output `shows the following

```
[root@wazuh-server /]# filebeat test output
elasticsearch: https://127.0.0.1:9200...
  parse url... OK
  connection...
    parse host... OK
    dns lookup... OK
    addresses: 127.0.0.1
    dial up... OK
  TLS...
    security: server's certificate chain verification is enabled
    handshake... OK
    TLS version: TLSv1.3
    dial up... OK
  talk to server... ERROR Get "https://127.0.0.1:9200": remote error: tls: unknown certificate

```

```
[root@wazuh-server /]# cat /etc/filebeat/filebeat.yml
# Wazuh - Filebeat configuration file
output.elasticsearch.hosts:
        - 127.0.0.1:9200
#        - <elasticsearch_ip_node_2>:9200
#        - <elasticsearch_ip_node_3>:9200

output.elasticsearch:
  protocol: https
  username: admin
  password: xxxxxxx
  ssl.certificate_authorities:
    - /etc/filebeat/certs/root-ca.pem
  ssl.certificate: "/etc/filebeat/certs/wazuh-server.pem"
  ssl.key: "/etc/filebeat/certs/wazuh-server-key.pem"
setup.template.json.enabled: true
setup.template.json.path: '/etc/filebeat/wazuh-template.json'
setup.template.json.name: 'wazuh'
setup.ilm.overwrite: true
setup.ilm.enabled: false

filebeat.modules:
  - module: wazuh
    alerts:
      enabled: true
    archives:
      enabled: false

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
[root@wazuh-server /]#

```

**Comment by AlexRuiz7** [comment]
Hi @luffysan92 

That's not good.

I noticed that there was a mistake in my previous comment, as the commands to deploy the certificates for the wazuh-server was mentioning the dashboard certificates instead.

I've fixed that. Please double-check the commands make sense and try again, and also, that the paths in the config files must the certificates, this is, the paths in the `/etc/wazuh-dashboard/opensearch_dashboards.yml`, `etc/filebeat/filebeat.yml` and the `/etc/wazuh-indexer/opensearch.yml` files.

I've reviewed that the commands in https://github.com/wazuh/wazuh-dashboard/issues/57#issuecomment-1542479225 match the paths of your config files, but I might have overlooked something.

My most sincere apologies.

**Comment by luffysan92** [comment]
Hi @AlexRuiz7 

I have deleted the certs and distributed again unfortunately not only do I still have wazuh dashboard server not ready but `filebeat test output` shows the following now 

```
[root@wazuh-server /]# filebeat test output
elasticsearch: https://127.0.0.1:9200...
  parse url... OK
  connection...
    parse host... OK
    dns lookup... OK
    addresses: 127.0.0.1
    dial up... OK
  TLS...
    security: server's certificate chain verification is enabled
    handshake... ERROR x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "Wazuh")
[root@wazuh-server /]#
```

Excuse the late reponse it has been a long week. 

Regards

**Comment by AlexRuiz7** [comment]
I need to look for more information about this new problem. I'll be back to you as soon as possible.

Thanks for your patience.

**Comment by luffysan92** [comment]
Hi @AlexRuiz7 thanks for pointing that out. Filebeat test output all ok now after I changed the port. I ran the logs and I dont see an error anymore check below.

```
: 457.4mb[0.8%], all indices on this node will be marked read-only
[2023-05-23T13:06:17,250][WARN ][o.o.s.a.BackendRegistry  ] [node-1] Authentication finally failed for kibanaserver from 127.0.0.1:52456
[2023-05-23T13:06:19,750][WARN ][o.o.s.a.BackendRegistry  ] [node-1] Authentication finally failed for kibanaserver from 127.0.0.1:52456
[2023-05-23T13:06:22,258][WARN ][o.o.s.a.BackendRegistry  ] [node-1] Authentication finally failed for kibanaserver from 127.0.0.1:52456
[2023-05-23T13:06:24,761][WARN ][o.o.s.a.BackendRegistry  ] [node-1] Authentication finally failed for kibanaserver from 127.0.0.1:52456
[2023-05-23T13:06:27,276][WARN ][o.o.s.a.BackendRegistry  ] [node-1] Authentication finally failed for kibanaserver from 127.0.0.1:52456
[2023-05-23T13:06:29,767][WARN ][o.o.s.a.BackendRegistry  ] [node-1] Authentication finally failed for kibanaserver from 127.0.0.1:52456
[2023-05-23T13:06:32,291][WARN ][o.o.s.a.BackendRegistry  ] [node-1] Authentication finally failed for kibanaserver from 127.0.0.1:52456
[2023-05-23T13:06:34,769][WARN ][o.o.s.a.BackendRegistry  ] [node-1] Authentication finally failed for kibanaserver from 127.0.0.1:52456
[2023-05-23T13:06:37,256][WARN ][o.o.s.a.BackendRegistry  ] [node-1] Authentication finally failed for kibanaserver from 127.0.0.1:52456
[2023-05-23T13:06:39,782][WARN ][o.o.s.a.BackendRegistry  ] [node-1] Authentication finally failed for kibanaserver from 127.0.0.1:52456
[2023-05-23T13:06:42,281][WARN ][o.o.s.a.BackendRegistry  ] [node-1] Authentication finally failed for kibanaserver from 127.0.0.1:52456
[2023-05-23T13:06:44,759][WARN ][o.o.s.a.BackendRegistry  ] [node-1] Authentication finally failed for kibanaserver from 127.0.0.1:52456
[2023-05-23T13:06:45,638][WARN ][o.o.c.r.a.DiskThresholdMonitor] [node-1] flood stage disk watermark [95%] exceeded on [a15kaIJQQha7HlHUaF1NxQ][node-1][/var/lib/wazuh-indexer/nodes/0] free: 456.8mb[0.8%], all indices on this node will be marked read-only
[2023-05-23T13:06:47,265][WARN ][o.o.s.a.BackendRegistry  ] [node-1] Authentication finally failed for kibanaserver from 127.0.0.1:52456
[2023-05-23T13:06:49,782][WARN ][o.o.s.a.BackendRegistry  ] [node-1] Authentication finally failed for kibanaserver from 127.0.0.1:52456
[2023-05-23T13:06:52,282][WARN ][o.o.s.a.BackendRegistry  ] [node-1] Authentication finally failed for kibanaserver from 127.0.0.1:52456
[2023-05-23T13:06:54,788][WARN ][o.o.s.a.BackendRegistry  ] [node-1] Authentication finally failed for kibanaserver from 127.0.0.1:52456
[2023-05-23T13:06:57,291][WARN ][o.o.s.a.BackendRegistry  ] [node-1] Authentication finally failed for kibanaserver from 127.0.0.1:52456
[2023-05-23T13:06:59,795][WARN ][o.o.s.a.BackendRegistry  ] [node-1] Authentication finally failed for kibanaserver from 127.0.0.1:52456
[2023-05-23T13:07:02,279][WARN ][o.o.s.a.BackendRegistry  ] [node-1] Authentication finally failed for kibanaserver from 127.0.0.1:52456
[2023-05-23T13:07:04,783][WARN ][o.o.s.a.BackendRegistry  ] [node-1] Authentication finally failed for kibanaserver from 127.0.0.1:52456
[2023-05-23T13:07:07,281][WARN ][o.o.s.a.BackendRegistry  ] [node-1] Authentication finally failed for kibanaserver from 127.0.0.1:52456
[2023-05-23T13:07:09,775][WARN ][o.o.s.a.BackendRegistry  ] [node-1] Authentication finally failed for kibanaserver from 127.0.0.1:52456
[2023-05-23T13:07:12,292][WARN ][o.o.s.a.BackendRegistry  ] [node-1] Authentication finally failed for kibanaserver from 127.0.0.1:52456
[2023-05-23T13:07:14,784][WARN ][o.o.s.a.BackendRegistry  ] [node-1] Authentication finally failed for kibanaserver from 127.0.0.1:52456
[2023-05-23T13:07:15,652][WARN ][o.o.c.r.a.DiskThresholdMonitor] [node-1] flood stage disk watermark [95%] exceeded on [a15kaIJQQha7HlHUaF1NxQ][node-1][/var/lib/wazuh-indexer/nodes/0] free: 455.9mb[0.8%], all indices on this node will be marked read-only
```
Still this didnt solve unable "Wazuh dashboard server is not ready yet" error.

**Comment by luffysan92** [comment]
Hi @AlexRuiz7 I have more bad news. wazuh-indexer and wazuh-manager are throwing errors now. Note there were no changes after yesterdays attempt which showed all services running. 

I ran systemctl status wazuh-indexer wazuh-manager wazuh-dashboard filebeat and results below.

```
[root@wazuh-server wazuh-user]# systemctl status wazuh-indexer wazuh-manager wazuh-dashboard filebeat
● wazuh-indexer.service - Wazuh-indexer
   Loaded: loaded (/usr/lib/systemd/system/wazuh-indexer.service; enabled; vendor preset: disabled)
   Active: failed (Result: resources) since Wed 2023-05-24 12:56:42 +13; 5h 52min ago
     Docs: https://documentation.wazuh.com
  Process: 823 ExecStart=/usr/share/wazuh-indexer/bin/systemd-entrypoint -p ${PID_DIR}/wazuh-indexer.pid --quiet (code=exited, status=143)
 Main PID: 823 (code=exited, status=143)

May 24 12:54:06 wazuh-server systemd-entrypoint[823]: at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242)
May 24 12:54:06 wazuh-server systemd-entrypoint[823]: at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404)
May 24 12:54:06 wazuh-server systemd-entrypoint[823]: at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180)
May 24 12:54:06 wazuh-server systemd-entrypoint[823]: at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171)
May 24 12:54:06 wazuh-server systemd-entrypoint[823]: at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104)
May 24 12:54:06 wazuh-server systemd-entrypoint[823]: at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
May 24 12:54:06 wazuh-server systemd-entrypoint[823]: at org.opensearch.cli.Command.main(Command.java:101)
May 24 12:54:06 wazuh-server systemd-entrypoint[823]: at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:137)
May 24 12:54:06 wazuh-server systemd-entrypoint[823]: at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:103)
May 24 12:54:06 wazuh-server systemd-entrypoint[823]: For complete error details, refer to the log at /var/log/wazuh-indexer/wazuh-cluster.log

● wazuh-manager.service - Wazuh manager
   Loaded: loaded (/usr/lib/systemd/system/wazuh-manager.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2023-05-24 13:24:26 +13; 5h 24min ago
  Process: 2943 ExecStop=/usr/bin/env /var/ossec/bin/wazuh-control stop (code=exited, status=1/FAILURE)
  Process: 2994 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=1/FAILURE)
   CGroup: /system.slice/wazuh-manager.service
           ├─1433 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
           ├─1455 /var/ossec/bin/wazuh-integratord
           ├─1476 /var/ossec/bin/wazuh-authd
           ├─1490 /var/ossec/bin/wazuh-db
           ├─1518 /var/ossec/bin/wazuh-execd
           ├─1520 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
           ├─1523 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
           ├─1539 /var/ossec/bin/wazuh-maild
           ├─1545 /var/ossec/bin/wazuh-analysisd
           ├─1559 /var/ossec/bin/wazuh-syscheckd
           ├─1578 /var/ossec/bin/wazuh-remoted
           ├─1656 /var/ossec/bin/wazuh-logcollector
           ├─1673 /var/ossec/bin/wazuh-monitord
           ├─1689 /var/ossec/bin/wazuh-modulesd
           └─1871 rpm -qa xorg-x11-server*

May 24 13:24:26 wazuh-server env[2994]: 2023/05/24 13:24:26 wazuh-modulesd: CRITICAL: Couldn't create PID file: (No space left on device)
May 24 13:24:26 wazuh-server env[2994]: 2023/05/24 13:24:26 wazuh-modulesd: ERROR: Couldn't delete PID file.
May 24 13:24:26 wazuh-server env[2994]: wazuh-modulesd: Configuration error. Exiting
May 24 13:24:26 wazuh-server env[2994]: touch: cannot touch ‘/var/ossec/var/run/wazuh-modulesd.failed’: No space left on device

● wazuh-dashboard.service - wazuh-dashboard
   Loaded: loaded (/etc/systemd/system/wazuh-dashboard.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2023-05-24 12:53:37 +13; 5h 55min ago
 Main PID: 401 (node)
   CGroup: /system.slice/wazuh-dashboard.service
           └─401 /usr/share/wazuh-dashboard/bin/../node/bin/node --no-warnings --max-http-header-size=65536 --unhandled-rejections=warn /usr/share/wazuh-dashboard/bin/../src/cli/dist -c ...

May 24 18:48:31 wazuh-server opensearch-dashboards[401]: {"type":"log","@timestamp":"2023-05-24T05:48:31Z","tags":["error","opensearch","data"],"pid":401,"message":"[Connectio....0.1:9200"}
May 24 18:48:34 wazuh-server opensearch-dashboards[401]: {"type":"log","@timestamp":"2023-05-24T05:48:34Z","tags":["error","opensearch","data"],"pid":401,"message":"[Connectio....0.1:9200"}
May 24 18:48:36 wazuh-server opensearch-dashboards[401]: {"type":"log","@timestamp":"2023-05-24T05:48:36Z","tags":["error","opensearch","data"],"pid":401,"message":"[Connectio....0.1:9200"}
May 24 18:48:39 wazuh-server opensearch-dashboards[401]: {"type":"log","@timestamp":"2023-05-24T05:48:39Z","tags":["error","opensearch","data"],"pid":401,"message":"[Connectio....0.1:9200"}
May 24 18:48:41 wazuh-server opensearch-dashboards[401]: {"type":"log","@timestamp":"2023-05-24T05:48:41Z","tags":["error","opensearch","data"],"pid":401,"message":"[Connectio....0.1:9200"}
May 24 18:48:44 wazuh-server opensearch-dashboards[401]: {"type":"log","@timestamp":"2023-05-24T05:48:44Z","tags":["error","opensearch","data"],"pid":401,"message":"[Connectio....0.1:9200"}
May 24 18:48:46 wazuh-server opensearch-dashboards[401]: {"type":"log","@timestamp":"2023-05-24T05:48:46Z","tags":["error","opensearch","data"],"pid":401,"message":"[Connectio....0.1:9200"}
May 24 18:48:49 wazuh-server opensearch-dashboards[401]: {"type":"log","@timestamp":"2023-05-24T05:48:49Z","tags":["error","opensearch","data"],"pid":401,"message":"[Connectio....0.1:9200"}
May 24 18:48:51 wazuh-server opensearch-dashboards[401]: {"type":"log","@timestamp":"2023-05-24T05:48:51Z","tags":["error","opensearch","data"],"pid":401,"message":"[Connectio....0.1:9200"}
May 24 18:48:54 wazuh-server opensearch-dashboards[401]: {"type":"log","@timestamp":"2023-05-24T05:48:54Z","tags":["error","opensearch","data"],"pid":401,"message":"[Connectio....0.1:9200"}

● filebeat.service - Filebeat sends log files to Logstash or directly to Elasticsearch.
   Loaded: loaded (/usr/lib/systemd/system/filebeat.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2023-05-24 12:53:42 +13; 5h 55min ago
     Docs: https://www.elastic.co/products/beats/filebeat
 Main PID: 826 (filebeat)
   CGroup: /system.slice/filebeat.service
           └─826 /usr/share/filebeat/bin/filebeat --environment systemd -c /etc/filebeat/filebeat.yml --path.home /usr/share/filebeat --path.config /etc/filebeat --path.data /var/lib/fil...

May 24 18:47:34 wazuh-server filebeat[826]: 2023-05-24 18:47:34.178770918 +1300 +13 m=+21231.182994430 write error: failed to write to file: write /var/log/filebeat/filebeat:...ft on device
May 24 18:47:39 wazuh-server filebeat[826]: 2023-05-24 18:47:39.895754728 +1300 +13 m=+21236.899978340 write error: failed to write to file: write /var/log/filebeat/filebeat:...ft on device
May 24 18:47:43 wazuh-server filebeat[826]: 2023-05-24 18:47:43.843363287 +1300 +13 m=+21240.847586799 write error: failed to write to file: write /var/log/filebeat/filebeat:...ft on device
May 24 18:47:44 wazuh-server filebeat[826]: 2023-05-24 18:47:44.895998321 +1300 +13 m=+21241.900221833 write error: failed to write to file: write /var/log/filebeat/filebeat:...ft on device
May 24 18:48:13 wazuh-server filebeat[826]: 2023-05-24 18:48:13.844156617 +1300 +13 m=+21270.848380029 write error: failed to write to file: write /var/log/filebeat/filebeat:...ft on device
May 24 18:48:27 wazuh-server filebeat[826]: 2023-05-24 18:48:27.761673013 +1300 +13 m=+21284.765896425 write error: failed to write to file: write /var/log/filebeat/filebeat:...ft on device
May 24 18:48:27 wazuh-server filebeat[826]: 2023-05-24 18:48:27.761817018 +1300 +13 m=+21284.766040530 write error: failed to write to file: write /var/log/filebeat/filebeat:...ft on device
May 24 18:48:27 wazuh-server filebeat[826]: 2023-05-24 18:48:27.762254835 +1300 +13 m=+21284.766478447 write error: failed to write to file: write /var/log/filebeat/filebeat:...ft on device
May 24 18:48:27 wazuh-server filebeat[826]: 2023-05-24 18:48:27.762522145 +1300 +13 m=+21284.766745757 write error: failed to write to file: write /var/log/filebeat/filebeat:...ft on device
May 24 18:48:43 wazuh-server filebeat[826]: 2023-05-24 18:48:43.846135492 +1300 +13 m=+21300.850358904 write error: failed to write to file: write /var/log/filebeat/filebeat:...ft on device
Hint: Some lines were ellipsized, use -l to show in full.
[root@wazuh-server wazuh-user]#
```
I tried to restart wazuh indexer but this came up. Same error with wazuh-manager.
```
[root@wazuh-server wazuh-user]# systemctl restart wazuh-indexer
Job for wazuh-indexer.service failed because a configured resource limit was exceeded. See "systemctl status wazuh-indexer.service" and "journalctl -xe" for details.
[root@wazuh-server wazuh-user]#
```

**Comment by AlexRuiz7** [comment]
Hello @luffysan92 

Looks the OVA storage has been filled up: `No space left on device`.

As there are several problems here which we do not manage to fix, I wonder if using a fresh OVA at version 4.4 and discard this one would be an option for you.

Regards
Alex

**Comment by Ooonsta** [comment]
I notice that you got into quite a mess here? I was just reading through https://github.com/wazuh/wazuh-packages/issues/1962 and noted the part about permissions issues on "/etc/wazuh-indexer/backup/" (rw root:root). I simply deleted this directory - 
rm -rf /etc/wazuh-indexer/backup/
and then I was able to restart my indexer and get everything back up and running again. Perhaps the original problem could have been this?
